const PREFIX = '@theme';

export const ON_CHANGE_THEME = `${PREFIX}/ON_CHANGE_THEME`;
export const ON_CHANGE_THEME_SUCCESS = `${PREFIX}/ON_CHANGE_THEME_SUCCESS`;
export const ON_CHANGE_THEME_ERROR = `${PREFIX}/ON_CHANGE_THEME_ERROR`;
